# Generated by Django 3.2.4 on 2021-07-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phn', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('doj', models.DateField(max_length=100)),
                ('accno', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=100)),
                ('payscale', models.DateField(max_length=100)),
            ],
        ),
    ]
