# Generated by Django 3.2.4 on 2021-07-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='f_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ifsc_code',
            new_name='ifsc',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='job_title',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='l_name',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='phn',
            new_name='mob',
        ),
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='payscale',
            field=models.CharField(max_length=100),
        ),
    ]
